#:import dp kivy.metrics.dp

<Coin>:
    size_hint: None, None
    size: dp(280), dp(280)
    pos: (self.parent.width/2 - self.width/2 + dp(3), self.parent.height/2 - self.height/2) if self.parent else (0,0)
    canvas.before:
        PushMatrix
        Scale:
            x: self.tilt_scale_x
            y: self.tilt_scale_y
            origin: self.center
    canvas:
        Color:
            rgba: 1, 1, 1, 1 
        Rectangle:
            pos: self.pos
            size: self.size
            texture: root.coin_texture  
    canvas.after:
        PopMatrix

<CyberCoinRoot>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
            texture: root.bg_texture

    # Flip-It Logo
    Image:
        size_hint: None, None
        size: dp(380), dp(180) 
        allow_stretch: True
        keep_ratio: True
        pos: (root.width/2 - self.width/2, coin.top - dp(75)) 
        texture: root.logo_tex

    # SIGNATUR
    Image:
        size_hint: None, None
        size: dp(90), dp(45) 
        pos_hint: {'x': 0.05, 'y': 0.05} 
        allow_stretch: True
        keep_ratio: True
        texture: root.sign_tex

    Coin:
        id: coin

    # BACKGROUND BUTTON
    Button:
        size_hint: None, None
        size: dp(85), dp(85)
        pos_hint: {'top': 0.98, 'right': 0.98} 
        background_color: 0, 0, 0, 0
        on_release: root.next_background()
        canvas.before:
            PushMatrix
            Scale:
                x: 0.85 if self.state == 'down' else 1.0
                y: 0.85 if self.state == 'down' else 1.0
                origin: self.center
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size
                texture: root.btn_bg_tex
        canvas.after:
            PopMatrix

    # MODE BUTTON
    Button:
        size_hint: None, None
        size: dp(130), dp(75) 
        pos_hint: {'right': 0.98, 'y': 0.03} 
        background_color: 0, 0, 0, 0
        on_release: root.toggle_mode()
        canvas.before:
            PushMatrix
            Scale:
                x: 0.9 if self.state == 'down' else 1.0
                y: 0.9 if self.state == 'down' else 1.0
                origin: self.center
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size
                texture: root.btn_mode_tex
        canvas.after:
            PopMatrix