name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04  # Spezifische Version für bessere Stabilität

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Date
        id: get-date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # Installiert benötigte Abhängigkeiten für den Runner
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev

      # Wir nutzen jetzt die offizielle Kivy Buildozer Action
      - name: Build with Buildozer
        uses: kivy/buildozer-action@master
        with:
          save_buildozer_dir: true
          # Der Befehl für den Debug-Build
          command: buildozer android debug
          repository_root: .

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CyberCoin-Android-${{ steps.get-date.outputs.date }}
          path: bin/*.apk
          if-no-files-found: error
